#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 15 17:09:47 2022

@author: AnantSrivastava
"""

from tkinter import*
root= Tk()

root.title("driving")
root.geometry("400x250")

root.configure(bg="white")
canvas=Canvas(root, width=400, hieght=250)
canvas.create_image(0,0, anchor=NW)
canvas.create_rectangle(0,0,400,45, fill="#F6091E")


label_heading=canvas.create_text(200,20, font('Times', 'bold italic'), text="dv", fill="white"
label_id_tag= canvas.create_text(25,60, font=('Times', '14', 'bold'), text="ID :")
label_name_tag= canvas.create_text(30,100, font=('Times', '12', 'bold'), text="Name :")
label_dob_tag= canvas.create_text(52,120, font=('Times', '12', 'bold'), text="Date Of Birth :")
label_pin_tag= canvas.create_text(32,140, font=('Times', '12', 'bold'), text="pin no. :")
label_address_tag= canvas.create_text(36,160, font=('Times', '12', 'bold'), text="Adress :")
label_vehicle_type_tag= canvas.create_text(155,180, font=('Times', '12', 'bold'), text="Authorisation to drive the fallowing vehicls :")
                                 
label_id_tag=Label(root)
label_name_tag=Label(root)
label_dob_tag=Label(root)
label_pin_tag=Label(root)
label_address_tag=Label(root)
label_vehicle_type_tag=Label(root)


def myLicense():
    id_value=1938287638763
    print(type(id_value))
    name=jamal
    print(type(name))
    dob=9/11/2001
    print(type(dob))
    pin=123456
    print(type(pin))
    address=HONG KONG, china
    print(type(address))
    vt=["two","four"]
    print(type(vt))
    
    
    label_id_tag['text']=id_value
    label_name_tag['text']=name
    label_dob_tag['text']=dob
    label_pin_tag['text']=pin
    label_address_tag['text']=address
    label_vehicle_type_tag['text']=vt
    
    
    button1= Button(root, text="show my license", command myLicense)
    
    button1.configure(width=20, activebackground="#9EC6EE", relief=FLAT)
    button1_window=canvas.create_window(200,235, anchor=CENTER, window=button1)
    label_id_window=canvas.create_window(200,235, anchor=CENTER, window=label_id)
    label_name_window=canvas.create_window(200,235, anchor=CENTER, window=label_name)
    label_dob_window=canvas.create_window(200,235, anchor=CENTER, window=label_dob)
    label_pin_window=canvas.create_window(200,235, anchor=CENTER, window=label_pin)
    label_address_window=canvas.create_window(200,235, anchor=CENTER, window=label_address)
    label_vehicle_type_window=canvas.create_window(200,235, anchor=CENTER, window=vt)
    root.mainloop()